import type {
  AIAgent,
  ReplayEvent,
  ScannedApp,
} from '@/types';

export const MOCK_AGENTS: AIAgent[] = [
  {
    id: 'threat-agent',
    name: 'Threat Agent',
    role: 'Permission risk analysis and threat detection',
    status: 'active',
    confidenceScore: 94,
    currentActivity: 'Standing by to analyze permission profiles from next device scan',
    lastAction: 'Permission threat pattern database loaded',
    iconKey: 'shield-alert',
    color: '#FF3B5C',
  },
  {
    id: 'network-agent',
    name: 'Network Agent',
    role: 'Tracker SDK detection and network risk analysis',
    status: 'scanning',
    confidenceScore: 88,
    currentActivity: 'Monitoring for new app installs via package broadcast receiver',
    lastAction: 'Tracker signature catalog updated',
    iconKey: 'network',
    color: '#00D4FF',
  },
  {
    id: 'privacy-coach',
    name: 'Privacy Coach',
    role: 'AI threat explanation and user briefing',
    status: 'active',
    confidenceScore: 97,
    currentActivity: 'Ready to generate AI analysis for detected permission threats',
    lastAction: 'AI analysis engine initialized',
    iconKey: 'brain',
    color: '#7B61FF',
  },
  {
    id: 'automation-agent',
    name: 'Automation Agent',
    role: 'Package monitoring and scan automation',
    status: 'idle',
    confidenceScore: 91,
    currentActivity: 'Package monitor receiver registered, awaiting install events',
    lastAction: 'Package monitor initialized',
    iconKey: 'zap',
    color: '#BF00FF',
  },
  {
    id: 'behavior-agent',
    name: 'Behavior Agent',
    role: 'Permission anomaly scoring and behavioral analysis',
    status: 'scanning',
    confidenceScore: 82,
    currentActivity: 'Permission anomaly baseline model loaded and ready',
    lastAction: 'Risk scoring weights calibrated',
    iconKey: 'activity',
    color: '#FFB800',
  },
];

export const MOCK_REPLAY_EVENTS: ReplayEvent[] = [
  {
    id: 'rp_init',
    title: 'System Ready',
    description: 'OMNYX permission intelligence engine initialized. Run a device scan to populate this archive.',
    riskChange: 0,
    riskLevel: 'safe',
    timestamp: new Date(Date.now() - 60 * 1000),
    agentResponse: 'All agents standing by. Scan the device to generate real privacy intelligence events.',
  },
];

export const MOCK_SCANNED_APPS: ScannedApp[] = [
  {
    id: '1',
    appName: 'Instagram',
    packageName: 'com.instagram.android',
    riskScore: 78,
    riskLevel: 'high',
    permissions: [
      { name: 'CAMERA', dangerous: true, category: 'camera' },
      { name: 'RECORD_AUDIO', dangerous: true, category: 'microphone' },
      { name: 'ACCESS_FINE_LOCATION', dangerous: true, category: 'location' },
      { name: 'READ_CONTACTS', dangerous: true, category: 'contacts' },
    ],
    lastSeen: new Date(),
  },
  {
    id: '2',
    appName: 'TikTok',
    packageName: 'com.zhiliaoapp.musically',
    riskScore: 91,
    riskLevel: 'critical',
    permissions: [
      { name: 'READ_CLIPBOARD', dangerous: true, category: 'system' },
      { name: 'RECORD_AUDIO', dangerous: true, category: 'microphone' },
      { name: 'ACCESS_FINE_LOCATION', dangerous: true, category: 'location' },
      { name: 'READ_CONTACTS', dangerous: true, category: 'contacts' },
      { name: 'CAMERA', dangerous: true, category: 'camera' },
    ],
    lastSeen: new Date(),
  },
  {
    id: '3',
    appName: 'FaceApp',
    packageName: 'io.faceapp',
    riskScore: 95,
    riskLevel: 'critical',
    permissions: [
      { name: 'CAMERA', dangerous: true, category: 'camera' },
      { name: 'READ_EXTERNAL_STORAGE', dangerous: false, category: 'storage' },
      { name: 'INTERNET', dangerous: false, category: 'network' },
    ],
    lastSeen: new Date(),
  },
];
