import type {
  ThreatEvent,
  AIAgent,
  ReplayEvent,
  ScannedApp,
  PrivacyScoreData,
} from '@/types';

export const MOCK_THREAT_EVENTS: ThreatEvent[] = [
  {
    id: '1',
    appName: 'Instagram',
    packageName: 'com.instagram.android',
    eventType: 'microphone_access',
    riskLevel: 'high',
    description: 'Instagram accessed microphone while running in background',
    aiExplanation:
      'This behavior matches known behavioral audio fingerprinting patterns. Instagram has no legitimate need for microphone access during background operation. The timing and duration of this access aligns with advertising data collection routines documented in prior research.',
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
    resolved: false,
  },
  {
    id: '2',
    appName: 'TikTok',
    packageName: 'com.zhiliaoapp.musically',
    eventType: 'clipboard_read',
    riskLevel: 'critical',
    description: 'TikTok read clipboard content 14 times in under 3 minutes',
    aiExplanation:
      'Clipboard polling at this frequency indicates systematic data harvesting. Content copied to clipboard may include passwords, bank details, personal messages, or tokens from other applications. This pattern has been linked to cross-app surveillance.',
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
    resolved: false,
  },
  {
    id: '3',
    appName: 'FaceApp',
    packageName: 'io.faceapp',
    eventType: 'network_request',
    riskLevel: 'critical',
    description: 'FaceApp transmitted 47MB of data to servers in a foreign jurisdiction',
    aiExplanation:
      'Large outbound transfers to servers in regions with limited data protection laws are a significant risk. The payload volume suggests full facial biometric transmission rather than lightweight metadata. Biometric data collected this way is difficult to revoke.',
    timestamp: new Date(Date.now() - 8 * 60 * 1000),
    resolved: true,
  },
  {
    id: '4',
    appName: 'Weather Pro',
    packageName: 'com.weatherpro.android',
    eventType: 'location_access',
    riskLevel: 'medium',
    description: 'Weather Pro accessed precise GPS location 23 times today',
    aiExplanation:
      'Location polling far exceeds what weather services require. At this granularity and frequency, the data is sufficient to reconstruct daily routines, home and work addresses, and movement patterns. This is consistent with behavioral profiling for ad targeting.',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    resolved: false,
  },
  {
    id: '5',
    appName: 'FlashLight Pro',
    packageName: 'com.flashlight.pro',
    eventType: 'suspicious_permission',
    riskLevel: 'high',
    description: 'Flashlight app requesting contacts, microphone, and location access',
    aiExplanation:
      'A flashlight utility has zero legitimate need for contacts, microphone, or location permissions. This combination is a textbook signature of a data harvesting trojan disguised as a utility. Recommend immediate review and removal.',
    timestamp: new Date(Date.now() - 22 * 60 * 1000),
    resolved: false,
  },
  {
    id: '6',
    appName: 'Facebook',
    packageName: 'com.facebook.katana',
    eventType: 'tracker_detected',
    riskLevel: 'medium',
    description: 'Meta SDK detected running inside 12 other installed apps',
    aiExplanation:
      'The Meta tracking SDK embedded in third-party apps enables cross-application behavioral profiling. Even without opening Facebook, your activity across those 12 apps is being reported to Meta servers in real time.',
    timestamp: new Date(Date.now() - 35 * 60 * 1000),
    resolved: false,
  },
  {
    id: '7',
    appName: 'Spotify',
    packageName: 'com.spotify.music',
    eventType: 'background_activity',
    riskLevel: 'low',
    description: 'Spotify running background processes at 3:42 AM',
    aiExplanation:
      'Unusual background activity during sleep hours. While Spotify maintains playlist sync, 3AM processing warrants monitoring. Activity volume exceeds expected sync operations by 340%.',
    timestamp: new Date(Date.now() - 60 * 60 * 1000),
    resolved: false,
  },
];

export const MOCK_AGENTS: AIAgent[] = [
  {
    id: 'threat-agent',
    name: 'Threat Agent',
    role: 'Real-time surveillance detection',
    status: 'active',
    confidenceScore: 94,
    currentActivity: 'Analyzing Instagram background process patterns across 3 sessions',
    lastAction: 'Flagged microphone access at 14:32',
    iconKey: 'shield-alert',
    color: '#FF3B5C',
  },
  {
    id: 'network-agent',
    name: 'Network Agent',
    role: 'Traffic analysis and tracker blocking',
    status: 'scanning',
    confidenceScore: 88,
    currentActivity: 'Deep inspection on 3 suspicious outbound connections',
    lastAction: 'Blocked tracker.doubleclick.net',
    iconKey: 'network',
    color: '#00D4FF',
  },
  {
    id: 'privacy-coach',
    name: 'Privacy Coach',
    role: 'AI threat explanation and user briefing',
    status: 'active',
    confidenceScore: 97,
    currentActivity: 'Generating risk report for TikTok clipboard access pattern',
    lastAction: 'Delivered threat briefing to user',
    iconKey: 'brain',
    color: '#7B61FF',
  },
  {
    id: 'automation-agent',
    name: 'Automation Agent',
    role: 'Autonomous privacy response system',
    status: 'idle',
    confidenceScore: 91,
    currentActivity: 'Monitoring permission change triggers across 47 apps',
    lastAction: 'Activated Ghost Mode protocol at 02:15',
    iconKey: 'zap',
    color: '#BF00FF',
  },
  {
    id: 'behavior-agent',
    name: 'Behavior Agent',
    role: 'Behavioral anomaly detection',
    status: 'scanning',
    confidenceScore: 82,
    currentActivity: 'Building baseline model from 14 days of usage data',
    lastAction: 'Detected anomaly in FaceApp data transfer volume',
    iconKey: 'activity',
    color: '#FFB800',
  },
];

export const MOCK_REPLAY_EVENTS: ReplayEvent[] = [
  {
    id: '1',
    title: 'Critical Threat Neutralized',
    description: 'TikTok clipboard harvesting blocked by Automation Agent',
    riskChange: -18,
    riskLevel: 'critical',
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
    appName: 'TikTok',
    agentResponse: 'Automation Agent revoked clipboard permission and flagged for review.',
  },
  {
    id: '2',
    title: 'Suspicious Permission Detected',
    description: 'FlashLight Pro requesting 4 dangerous permissions simultaneously',
    riskChange: 12,
    riskLevel: 'high',
    timestamp: new Date(Date.now() - 22 * 60 * 1000),
    appName: 'FlashLight Pro',
    agentResponse: 'Threat Agent initiated app isolation protocol.',
  },
  {
    id: '3',
    title: 'Privacy Score Improved',
    description: 'Ghost Mode activation reduced tracking surface by 73%',
    riskChange: -24,
    riskLevel: 'safe',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    agentResponse: 'All 5 agents confirmed reduced threat exposure.',
  },
  {
    id: '4',
    title: 'Network Anomaly Blocked',
    description: 'FaceApp attempted data exfiltration to 185.220.x.x',
    riskChange: 8,
    riskLevel: 'critical',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    appName: 'FaceApp',
    agentResponse: 'Network Agent blocked outbound connection. 47MB transfer prevented.',
  },
  {
    id: '5',
    title: 'Tracker Network Mapped',
    description: 'Meta SDK found running inside 12 installed applications',
    riskChange: 6,
    riskLevel: 'medium',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    agentResponse: 'Behavior Agent documented cross-app tracking relationships.',
  },
  {
    id: '6',
    title: 'Sleep Mode Activated',
    description: 'AI automatically enabled Sleep Mode at midnight',
    riskChange: -15,
    riskLevel: 'safe',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    agentResponse: 'Automation Agent suspended 8 background processes.',
  },
];

export const MOCK_PRIVACY_SCORE: PrivacyScoreData = {
  current: 67,
  previous: 54,
  trend: 'improving',
  breakdown: {
    permissions: 58,
    trackers: 72,
    networkActivity: 65,
    dataCollection: 73,
  },
};

export const MOCK_SCANNED_APPS: ScannedApp[] = [
  {
    id: '1',
    appName: 'Instagram',
    packageName: 'com.instagram.android',
    riskScore: 78,
    riskLevel: 'high',
    permissions: [
      { name: 'CAMERA', dangerous: true, category: 'camera' },
      { name: 'RECORD_AUDIO', dangerous: true, category: 'microphone' },
      { name: 'ACCESS_FINE_LOCATION', dangerous: true, category: 'location' },
      { name: 'READ_CONTACTS', dangerous: true, category: 'contacts' },
    ],
    lastSeen: new Date(),
  },
  {
    id: '2',
    appName: 'TikTok',
    packageName: 'com.zhiliaoapp.musically',
    riskScore: 91,
    riskLevel: 'critical',
    permissions: [
      { name: 'READ_CLIPBOARD', dangerous: true, category: 'system' },
      { name: 'RECORD_AUDIO', dangerous: true, category: 'microphone' },
      { name: 'ACCESS_FINE_LOCATION', dangerous: true, category: 'location' },
      { name: 'READ_CONTACTS', dangerous: true, category: 'contacts' },
      { name: 'CAMERA', dangerous: true, category: 'camera' },
    ],
    lastSeen: new Date(),
  },
  {
    id: '3',
    appName: 'FaceApp',
    packageName: 'io.faceapp',
    riskScore: 95,
    riskLevel: 'critical',
    permissions: [
      { name: 'CAMERA', dangerous: true, category: 'camera' },
      { name: 'READ_EXTERNAL_STORAGE', dangerous: false, category: 'storage' },
      { name: 'INTERNET', dangerous: false, category: 'network' },
    ],
    lastSeen: new Date(),
  },
];
