import type {
  AIAgent,
  ReplayEvent,
  ScannedApp,
} from '@/types';

export const MOCK_AGENTS: AIAgent[] = [
  {
    id: 'threat-agent',
    name: 'Threat Agent',
    role: 'Real-time surveillance detection',
    status: 'active',
    confidenceScore: 94,
    currentActivity: 'Analyzing Instagram background process patterns across 3 sessions',
    lastAction: 'Flagged microphone access at 14:32',
    iconKey: 'shield-alert',
    color: '#FF3B5C',
  },
  {
    id: 'network-agent',
    name: 'Network Agent',
    role: 'Traffic analysis and tracker blocking',
    status: 'scanning',
    confidenceScore: 88,
    currentActivity: 'Deep inspection on 3 suspicious outbound connections',
    lastAction: 'Blocked tracker.doubleclick.net',
    iconKey: 'network',
    color: '#00D4FF',
  },
  {
    id: 'privacy-coach',
    name: 'Privacy Coach',
    role: 'AI threat explanation and user briefing',
    status: 'active',
    confidenceScore: 97,
    currentActivity: 'Generating risk report for TikTok clipboard access pattern',
    lastAction: 'Delivered threat briefing to user',
    iconKey: 'brain',
    color: '#7B61FF',
  },
  {
    id: 'automation-agent',
    name: 'Automation Agent',
    role: 'Autonomous privacy response system',
    status: 'idle',
    confidenceScore: 91,
    currentActivity: 'Monitoring permission change triggers across 47 apps',
    lastAction: 'Activated Ghost Mode protocol at 02:15',
    iconKey: 'zap',
    color: '#BF00FF',
  },
  {
    id: 'behavior-agent',
    name: 'Behavior Agent',
    role: 'Behavioral anomaly detection',
    status: 'scanning',
    confidenceScore: 82,
    currentActivity: 'Building baseline model from 14 days of usage data',
    lastAction: 'Detected anomaly in FaceApp data transfer volume',
    iconKey: 'activity',
    color: '#FFB800',
  },
];

export const MOCK_REPLAY_EVENTS: ReplayEvent[] = [
  {
    id: '1',
    title: 'Critical Threat Neutralized',
    description: 'TikTok clipboard harvesting blocked by Automation Agent',
    riskChange: -18,
    riskLevel: 'critical',
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
    appName: 'TikTok',
    agentResponse: 'Automation Agent revoked clipboard permission and flagged for review.',
  },
  {
    id: '2',
    title: 'Suspicious Permission Detected',
    description: 'FlashLight Pro requesting 4 dangerous permissions simultaneously',
    riskChange: 12,
    riskLevel: 'high',
    timestamp: new Date(Date.now() - 22 * 60 * 1000),
    appName: 'FlashLight Pro',
    agentResponse: 'Threat Agent initiated app isolation protocol.',
  },
  {
    id: '3',
    title: 'Privacy Score Improved',
    description: 'Ghost Mode activation reduced tracking surface by 73%',
    riskChange: -24,
    riskLevel: 'safe',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    agentResponse: 'All 5 agents confirmed reduced threat exposure.',
  },
  {
    id: '4',
    title: 'Network Anomaly Blocked',
    description: 'FaceApp attempted data exfiltration to 185.220.x.x',
    riskChange: 8,
    riskLevel: 'critical',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    appName: 'FaceApp',
    agentResponse: 'Network Agent blocked outbound connection. 47MB transfer prevented.',
  },
  {
    id: '5',
    title: 'Tracker Network Mapped',
    description: 'Meta SDK found running inside 12 installed applications',
    riskChange: 6,
    riskLevel: 'medium',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    agentResponse: 'Behavior Agent documented cross-app tracking relationships.',
  },
  {
    id: '6',
    title: 'Sleep Mode Activated',
    description: 'AI automatically enabled Sleep Mode at midnight',
    riskChange: -15,
    riskLevel: 'safe',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    agentResponse: 'Automation Agent suspended 8 background processes.',
  },
];

export const MOCK_SCANNED_APPS: ScannedApp[] = [
  {
    id: '1',
    appName: 'Instagram',
    packageName: 'com.instagram.android',
    riskScore: 78,
    riskLevel: 'high',
    permissions: [
      { name: 'CAMERA', dangerous: true, category: 'camera' },
      { name: 'RECORD_AUDIO', dangerous: true, category: 'microphone' },
      { name: 'ACCESS_FINE_LOCATION', dangerous: true, category: 'location' },
      { name: 'READ_CONTACTS', dangerous: true, category: 'contacts' },
    ],
    lastSeen: new Date(),
  },
  {
    id: '2',
    appName: 'TikTok',
    packageName: 'com.zhiliaoapp.musically',
    riskScore: 91,
    riskLevel: 'critical',
    permissions: [
      { name: 'READ_CLIPBOARD', dangerous: true, category: 'system' },
      { name: 'RECORD_AUDIO', dangerous: true, category: 'microphone' },
      { name: 'ACCESS_FINE_LOCATION', dangerous: true, category: 'location' },
      { name: 'READ_CONTACTS', dangerous: true, category: 'contacts' },
      { name: 'CAMERA', dangerous: true, category: 'camera' },
    ],
    lastSeen: new Date(),
  },
  {
    id: '3',
    appName: 'FaceApp',
    packageName: 'io.faceapp',
    riskScore: 95,
    riskLevel: 'critical',
    permissions: [
      { name: 'CAMERA', dangerous: true, category: 'camera' },
      { name: 'READ_EXTERNAL_STORAGE', dangerous: false, category: 'storage' },
      { name: 'INTERNET', dangerous: false, category: 'network' },
    ],
    lastSeen: new Date(),
  },
];
