import type { PermissionDefinition } from '@/types/permissions';

export const PERMISSION_DB: Record<string, PermissionDefinition> = {
  // ── LOCATION ──────────────────────────────────────────────────────────────
  ACCESS_FINE_LOCATION: {
    androidName: 'android.permission.ACCESS_FINE_LOCATION',
    shortName: 'ACCESS_FINE_LOCATION',
    category: 'location',
    riskWeight: 70,
    isDangerous: true,
    isSpecial: false,
    label: 'Precise Location',
    threat: 'Tracks exact GPS position to meter accuracy',
  },
  ACCESS_COARSE_LOCATION: {
    androidName: 'android.permission.ACCESS_COARSE_LOCATION',
    shortName: 'ACCESS_COARSE_LOCATION',
    category: 'location',
    riskWeight: 45,
    isDangerous: true,
    isSpecial: false,
    label: 'Approximate Location',
    threat: 'Tracks general area via cell tower and WiFi',
  },
  ACCESS_BACKGROUND_LOCATION: {
    androidName: 'android.permission.ACCESS_BACKGROUND_LOCATION',
    shortName: 'ACCESS_BACKGROUND_LOCATION',
    category: 'location',
    riskWeight: 88,
    isDangerous: true,
    isSpecial: false,
    label: 'Background Location',
    threat: 'Continuously tracks location even when app is closed',
  },

  // ── MICROPHONE ────────────────────────────────────────────────────────────
  RECORD_AUDIO: {
    androidName: 'android.permission.RECORD_AUDIO',
    shortName: 'RECORD_AUDIO',
    category: 'microphone',
    riskWeight: 78,
    isDangerous: true,
    isSpecial: false,
    label: 'Microphone',
    threat: 'Can record audio, voice, and ambient sound',
  },

  // ── CAMERA ────────────────────────────────────────────────────────────────
  CAMERA: {
    androidName: 'android.permission.CAMERA',
    shortName: 'CAMERA',
    category: 'camera',
    riskWeight: 65,
    isDangerous: true,
    isSpecial: false,
    label: 'Camera',
    threat: 'Can capture photos and video without visible indicator',
  },

  // ── CONTACTS ──────────────────────────────────────────────────────────────
  READ_CONTACTS: {
    androidName: 'android.permission.READ_CONTACTS',
    shortName: 'READ_CONTACTS',
    category: 'contacts',
    riskWeight: 72,
    isDangerous: true,
    isSpecial: false,
    label: 'Read Contacts',
    threat: 'Access to full contact database including phone numbers and emails',
  },
  WRITE_CONTACTS: {
    androidName: 'android.permission.WRITE_CONTACTS',
    shortName: 'WRITE_CONTACTS',
    category: 'contacts',
    riskWeight: 55,
    isDangerous: true,
    isSpecial: false,
    label: 'Modify Contacts',
    threat: 'Can add, edit, or delete contacts without notification',
  },

  // ── PHONE ─────────────────────────────────────────────────────────────────
  READ_PHONE_STATE: {
    androidName: 'android.permission.READ_PHONE_STATE',
    shortName: 'READ_PHONE_STATE',
    category: 'device_id',
    riskWeight: 62,
    isDangerous: true,
    isSpecial: false,
    label: 'Phone Identity',
    threat: 'Access to IMEI and device identifiers used for persistent tracking',
  },
  READ_CALL_LOG: {
    androidName: 'android.permission.READ_CALL_LOG',
    shortName: 'READ_CALL_LOG',
    category: 'phone',
    riskWeight: 82,
    isDangerous: true,
    isSpecial: false,
    label: 'Call History',
    threat: 'Reveals all incoming and outgoing call records and durations',
  },
  CALL_PHONE: {
    androidName: 'android.permission.CALL_PHONE',
    shortName: 'CALL_PHONE',
    category: 'phone',
    riskWeight: 68,
    isDangerous: true,
    isSpecial: false,
    label: 'Initiate Calls',
    threat: 'Can place phone calls without user interaction',
  },

  // ── SMS ───────────────────────────────────────────────────────────────────
  READ_SMS: {
    androidName: 'android.permission.READ_SMS',
    shortName: 'READ_SMS',
    category: 'sms',
    riskWeight: 88,
    isDangerous: true,
    isSpecial: false,
    label: 'Read Messages',
    threat: 'Access to all SMS including 2FA codes and banking OTPs',
  },
  RECEIVE_SMS: {
    androidName: 'android.permission.RECEIVE_SMS',
    shortName: 'RECEIVE_SMS',
    category: 'sms',
    riskWeight: 82,
    isDangerous: true,
    isSpecial: false,
    label: 'Intercept Messages',
    threat: 'Can silently intercept incoming SMS before you see them',
  },
  SEND_SMS: {
    androidName: 'android.permission.SEND_SMS',
    shortName: 'SEND_SMS',
    category: 'sms',
    riskWeight: 74,
    isDangerous: true,
    isSpecial: false,
    label: 'Send Messages',
    threat: 'Can send SMS messages and incur charges without consent',
  },

  // ── STORAGE ───────────────────────────────────────────────────────────────
  READ_EXTERNAL_STORAGE: {
    androidName: 'android.permission.READ_EXTERNAL_STORAGE',
    shortName: 'READ_EXTERNAL_STORAGE',
    category: 'storage',
    riskWeight: 45,
    isDangerous: true,
    isSpecial: false,
    label: 'Read Files',
    threat: 'Access to photos, documents, and downloads',
  },
  WRITE_EXTERNAL_STORAGE: {
    androidName: 'android.permission.WRITE_EXTERNAL_STORAGE',
    shortName: 'WRITE_EXTERNAL_STORAGE',
    category: 'storage',
    riskWeight: 40,
    isDangerous: true,
    isSpecial: false,
    label: 'Write Files',
    threat: 'Can write, modify, and delete files on device storage',
  },
  READ_MEDIA_IMAGES: {
    androidName: 'android.permission.READ_MEDIA_IMAGES',
    shortName: 'READ_MEDIA_IMAGES',
    category: 'storage',
    riskWeight: 50,
    isDangerous: true,
    isSpecial: false,
    label: 'Access Gallery',
    threat: 'Can read all photos and images in device gallery',
  },

  // ── SENSORS ───────────────────────────────────────────────────────────────
  BODY_SENSORS: {
    androidName: 'android.permission.BODY_SENSORS',
    shortName: 'BODY_SENSORS',
    category: 'sensors',
    riskWeight: 62,
    isDangerous: true,
    isSpecial: false,
    label: 'Body Sensors',
    threat: 'Reads health biometrics: heart rate, blood oxygen, movement',
  },
  ACTIVITY_RECOGNITION: {
    androidName: 'android.permission.ACTIVITY_RECOGNITION',
    shortName: 'ACTIVITY_RECOGNITION',
    category: 'sensors',
    riskWeight: 48,
    isDangerous: true,
    isSpecial: false,
    label: 'Physical Activity',
    threat: 'Monitors steps, exercise patterns, sleep behavior',
  },

  // ── CALENDAR ──────────────────────────────────────────────────────────────
  READ_CALENDAR: {
    androidName: 'android.permission.READ_CALENDAR',
    shortName: 'READ_CALENDAR',
    category: 'calendar',
    riskWeight: 56,
    isDangerous: true,
    isSpecial: false,
    label: 'Read Calendar',
    threat: 'Access to appointments, meetings, and personal schedule',
  },
  WRITE_CALENDAR: {
    androidName: 'android.permission.WRITE_CALENDAR',
    shortName: 'WRITE_CALENDAR',
    category: 'calendar',
    riskWeight: 45,
    isDangerous: true,
    isSpecial: false,
    label: 'Modify Calendar',
    threat: 'Can create, edit, or delete calendar events',
  },

  // ── BACKGROUND ────────────────────────────────────────────────────────────
  RECEIVE_BOOT_COMPLETED: {
    androidName: 'android.permission.RECEIVE_BOOT_COMPLETED',
    shortName: 'RECEIVE_BOOT_COMPLETED',
    category: 'background',
    riskWeight: 44,
    isDangerous: false,
    isSpecial: false,
    label: 'Auto-Start',
    threat: 'Automatically launches every time the device boots',
  },
  FOREGROUND_SERVICE: {
    androidName: 'android.permission.FOREGROUND_SERVICE',
    shortName: 'FOREGROUND_SERVICE',
    category: 'background',
    riskWeight: 34,
    isDangerous: false,
    isSpecial: false,
    label: 'Background Service',
    threat: 'Runs a persistent background process',
  },
  REQUEST_INSTALL_PACKAGES: {
    androidName: 'android.permission.REQUEST_INSTALL_PACKAGES',
    shortName: 'REQUEST_INSTALL_PACKAGES',
    category: 'package_management',
    riskWeight: 84,
    isDangerous: false,
    isSpecial: true,
    label: 'Install Applications',
    threat: 'Can silently download and install third-party software',
  },

  // ── SPECIAL ACCESS ────────────────────────────────────────────────────────
  SYSTEM_ALERT_WINDOW: {
    androidName: 'android.permission.SYSTEM_ALERT_WINDOW',
    shortName: 'SYSTEM_ALERT_WINDOW',
    category: 'overlay',
    riskWeight: 86,
    isDangerous: false,
    isSpecial: true,
    label: 'Draw Over Apps',
    threat: 'Can overlay UI on any screen, enabling credential phishing',
  },
  BIND_ACCESSIBILITY_SERVICE: {
    androidName: 'android.permission.BIND_ACCESSIBILITY_SERVICE',
    shortName: 'BIND_ACCESSIBILITY_SERVICE',
    category: 'accessibility',
    riskWeight: 96,
    isDangerous: false,
    isSpecial: true,
    label: 'Accessibility Control',
    threat: 'Full device control: reads screen, intercepts input, automates actions',
  },
  WRITE_SETTINGS: {
    androidName: 'android.permission.WRITE_SETTINGS',
    shortName: 'WRITE_SETTINGS',
    category: 'device_id',
    riskWeight: 64,
    isDangerous: false,
    isSpecial: true,
    label: 'Modify System Settings',
    threat: 'Can alter device configuration including network and display settings',
  },

  // ── NETWORK ───────────────────────────────────────────────────────────────
  INTERNET: {
    androidName: 'android.permission.INTERNET',
    shortName: 'INTERNET',
    category: 'network',
    riskWeight: 10,
    isDangerous: false,
    isSpecial: false,
    label: 'Internet Access',
    threat: 'Network access for data transmission',
  },
  ACCESS_WIFI_STATE: {
    androidName: 'android.permission.ACCESS_WIFI_STATE',
    shortName: 'ACCESS_WIFI_STATE',
    category: 'network',
    riskWeight: 22,
    isDangerous: false,
    isSpecial: false,
    label: 'WiFi State',
    threat: 'Can fingerprint network history for location inference',
  },
  ACCESS_NETWORK_STATE: {
    androidName: 'android.permission.ACCESS_NETWORK_STATE',
    shortName: 'ACCESS_NETWORK_STATE',
    category: 'network',
    riskWeight: 10,
    isDangerous: false,
    isSpecial: false,
    label: 'Network State',
    threat: 'Checks connectivity status',
  },
  CHANGE_WIFI_STATE: {
    androidName: 'android.permission.CHANGE_WIFI_STATE',
    shortName: 'CHANGE_WIFI_STATE',
    category: 'network',
    riskWeight: 36,
    isDangerous: false,
    isSpecial: false,
    label: 'Control WiFi',
    threat: 'Can enable, disable, or switch WiFi networks',
  },
  BLUETOOTH_SCAN: {
    androidName: 'android.permission.BLUETOOTH_SCAN',
    shortName: 'BLUETOOTH_SCAN',
    category: 'location',
    riskWeight: 42,
    isDangerous: true,
    isSpecial: false,
    label: 'Bluetooth Scan',
    threat: 'Can infer location by scanning nearby Bluetooth devices',
  },

  // ── BENIGN ────────────────────────────────────────────────────────────────
  VIBRATE: {
    androidName: 'android.permission.VIBRATE',
    shortName: 'VIBRATE',
    category: 'device_id',
    riskWeight: 5,
    isDangerous: false,
    isSpecial: false,
    label: 'Vibration',
    threat: 'Controls haptic motor',
  },
  WAKE_LOCK: {
    androidName: 'android.permission.WAKE_LOCK',
    shortName: 'WAKE_LOCK',
    category: 'background',
    riskWeight: 12,
    isDangerous: false,
    isSpecial: false,
    label: 'Keep Awake',
    threat: 'Prevents device from entering sleep mode',
  },
  FLASHLIGHT: {
    androidName: 'android.permission.FLASHLIGHT',
    shortName: 'FLASHLIGHT',
    category: 'device_id',
    riskWeight: 3,
    isDangerous: false,
    isSpecial: false,
    label: 'Flashlight',
    threat: 'Controls camera flash LED',
  },
  NFC: {
    androidName: 'android.permission.NFC',
    shortName: 'NFC',
    category: 'network',
    riskWeight: 28,
    isDangerous: false,
    isSpecial: false,
    label: 'NFC',
    threat: 'Near-field data exchange with contactless devices',
  },
  BLUETOOTH: {
    androidName: 'android.permission.BLUETOOTH',
    shortName: 'BLUETOOTH',
    category: 'network',
    riskWeight: 22,
    isDangerous: false,
    isSpecial: false,
    label: 'Bluetooth',
    threat: 'Wireless device pairing and audio streaming',
  },
  USE_BIOMETRIC: {
    androidName: 'android.permission.USE_BIOMETRIC',
    shortName: 'USE_BIOMETRIC',
    category: 'sensors',
    riskWeight: 36,
    isDangerous: false,
    isSpecial: false,
    label: 'Biometric Auth',
    threat: 'Uses fingerprint or face recognition for authentication',
  },
  POST_NOTIFICATIONS: {
    androidName: 'android.permission.POST_NOTIFICATIONS',
    shortName: 'POST_NOTIFICATIONS',
    category: 'notification',
    riskWeight: 15,
    isDangerous: false,
    isSpecial: false,
    label: 'Send Notifications',
    threat: 'Can display notifications to the user',
  },
};
